Repository warmachine028/magnifico, pull requests merged in 2024-08, with the labels that each got.

#8 feat: added SEO enhancements
  client/index.html
  client/src/pages/Home.jsx
  client/src/pages/Payment.jsx
Labels: enhancement, feature

#10 fix: check-pr-title.yml
  .github/workflows/check-pr-title.yml
Labels: enhancement, feature

#12 fix: pr-preview.yml
  .github/workflows/pr-preview.yml
Labels: 🛠 goal: fix, 🐞 bug

#16 docs: updated Introduction, Deployment, Tech-Stack section of readme
  README.md
Labels: documentation, 📄 aspect: text

#17 fix: disable PR Preview
  .github/workflows/pr-preview.yml
Labels: 🛠 goal: fix, 🐞 bug
